### ISSUE TITLE
app$get_screenshot() should auto-open the Plots tab in RStudio

### ISSUE THREAD

**Issue by daattali** [rstudio/shinytest2#197] opened 2022-05-03 01:01 UTC
Related to #196 

When generating any plot in RStudio, the Plots tab automatically becomes active so that we can see what we just plotted. It would be useful if this happened when shinytest2 takes a screenshot, because it took me a while to realize the screenshot was successful until I understood that I need to go hunt for it in the IDE :) Especially because I was looking at the Viewer (according to docs) when in fact it was in Plots

**Comment by schloerke** [comment] 2022-05-03 15:30
Are you wanting the `$get_screenshot(file = PNG_PATH)` to **also** open in the plots tab? Currently, if a file is provided, no screenshot will be displayed in the Plots tab.

`$get_screenshot(file = NULL)` auto opens the Plots tab when called interactively. I can reprex this expected behavior locally.

**Comment by daattali** [comment] 2022-05-03 15:43
> Are you wanting the `$get_screenshot(file = PNG_PATH)` to **also** open in the plots tab? Currently, if a file is provided, no screenshot will be displayed in the Plots tab.

No, I don't think when saving to file there's an expectation to see it 

> 
> `$get_screenshot(file = NULL)` auto opens the Plots tab when called interactively. I can reprex this expected behavior locally.

It doesn't do that for me. I'm using the latest stable RStudio release for Windows and the CRAN version for the package. Maybe it works in the daily builds or with the github version, would that make sense?

**Comment by schloerke** [comment] 2022-05-03 16:08
> It doesn't do that for me. I'm using the latest stable RStudio release for Windows and the CRAN version for the package.

I am on macOS and using an older build of RStudio IDE, 461.  I believe you said you had IDE version 498.

Hmmm, I haven't changed any code to displaying the screenshot in the Plots tab from what is on CRAN. 

Trying to debug... Can you open another tab besides `Plots` and then run `showimage::show_image(system.file("img", "Rlogo.png", package="png"))`? This opens the plots tab for me and displays the R logo.

The logic above is very similar to https://github.com/rstudio/shinytest2/blob/d8e4a491d78fc227c376e1a0c19799922b5d6c1d/R/app-driver-expect-screenshot.R#L49-L54

**Comment by daattali** [comment] 2022-05-03 16:25
Yes that works, that opens up the Plots tab and shows the image

**Comment by daattali** [comment] 2022-05-03 16:33
When I use `debug(shinytest2:::app_screenshot)` before calling `shinytest2::test_app()` and run the lines one by one, it does work. But when I just run `test_app()` without debugging the internal function and the test runs to completion, the plots tab never opens up.

Sorry.

🤷‍♂️

**Comment by schloerke** [comment] 2022-05-03 17:23
So weird!

May I have your setup to try to reprex on my side? Simple file/contents work for me and the command to execute work for me.  

Thank you!

**Comment by daattali** [comment] 2022-05-03 19:07
1. Create a plain `app.R`:

    ```
    library(shiny)
    shinyApp(
      ui = fluidPage(
        textInput("text", "text", "text"),
        textOutput("out")
      ),
      server = function(input, output) {
        output$out <- renderText(input$text)
      }
    )
    ```

2. Run `shinytest2::record_test()`

3. Modify the text input, click "Expect screenshot", then save & exit

4. Open the newly created `tests/testthat/test-shinytest2.R` file
 
5.  Add `app$get_screenshot()` after `spp$set_inputs()`, before `app$expect_screenshot()`. This is my resulting file:

    ```
    library(shinytest2)
    
    test_that("{shinytest2} recording: test1", {
      app <- AppDriver$new(variant = platform_variant(), name = "test1", height = 937,
          width = 1619)
      app$set_inputs(text = "texta")
      app$get_screenshot()
      app$expect_screenshot()
      app$expect_values()
    })
    ```

6. Run `shinytest2::test_app()`

The test passes, if I go to the Plots tab I see the screenshot, but it did not open that tab automatically.

**Comment by schloerke** [comment] 2022-05-03 19:39
I can reprex this! ... but I don't think this is a shinytest2 issue, but rather an IDE issue. 

Because it is an uncommon usage situation within a test and it works as expected interactively, I am going to close this issue and not repost the issue to `rstudio/rstudio`.

**Closed** 2022-05-03 19:40 UTC
Labels: wontfix

**Comment by daattali** [comment] 2022-05-03 21:37
Out of curiousity what specifically about this test caused the issue? Why were you not able to reproduce on your own before?

**Comment by schloerke** [comment] 2022-05-03 22:59
> Out of curiousity what specifically about this test caused the issue? 

I don't know. I also don't see a reason why it shouldn't work. This leads me to blame the IDE.

I did not test in terminal. I'll try that tomorrow. 

> Why were you not able to reproduce on your own before?

Calling `$get_screenshot(file = NULL)` within a test doesn't really achieve anything to me. So I didn't think to test it as the method worked interactively.

**Comment by daattali** [comment] 2022-05-03 23:37
My intended usecase was that throughout the testcase I can sprinkle some `get_screenshot()` so that (a) I can get a live view passive of what's going on but without actually being in the app (quicker/simpler than `$view()`) and (b) when the test finishes I'll have a few screenshots to replay to see what happened. Sort of like putting a bunch of `print()` statements when testing.

.... Actually this is a lie, my initial usecase was to just test out the functionality and see it. But afterwards I thought of the above ^

**Comment by schloerke** [comment] 2022-05-04 01:45
> My intended usecase was that throughout the testcase I can sprinkle some `get_screenshot()` so that (a) I can get a live view passive of what's going on but without actually being in the app (quicker/simpler than `$view()`) and (b) when the test finishes I'll have a few screenshots to replay to see what happened. Sort of like putting a bunch of `print()` statements when testing.

For the goal of "knowing what's going on without failing the test", I strongly recommend using `$expect_values()` which will add in a _debug_ screenshot snapshot file. 

This debug screenshot (ending in `_.png` with the same name) is a snapshot file that will never fail a test and is there to capture what the app looked like at the time of the call to `$expect_values()`. 

I recommend checking the `_.png` files into your Git repo for historical comparisons. (And ignoring `_.new.png` files. Only keeping the accepted debug png files)

**Comment by schloerke** [comment] 2022-05-04 14:51
Code within a testthat test...

Does not open Plots tab in IDE. (However, when visiting the Plots tab, the screenshot is there.)
```r
....
  ignore <- app$get_screenshot()
  app$expect_values()
....
```

```r
....
  showimage::show_image(system.file("img", "Rlogo.png", package="png"))
  app$expect_values()
....
```


------------------------------

Opens Plots tab in IDE
```r
....
  ignore <- app$get_screenshot()
  NULL
....
```
```r
....
  app$expect_values()
  ignore <- app$get_screenshot()
  NULL
....
```
```r
....
  showimage::show_image(system.file("img", "Rlogo.png", package="png"))
  NULL
....
```
```r
....
  app$expect_values()
  showimage::show_image(system.file("img", "Rlogo.png", package="png"))
  NULL
....
```


--------------------------

So it's not a printing situation where the last value is being displayed. 

🤯
